### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by YasogaN** [SnoozeThis/playground#14]
@SnoozeThis wait for 2 weeks -> assign to YasogaN@, say "Reminder"

**Comment by SnoozeThis** [comment]
Sorry, I don't understand "say Reminder"

**Comment by YasogaN** [comment]
@SnoozeThis wait for 2 weeks -> assign to YasogaN@, tell "Reminder"

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/nQ7eMOw7QQc) I will wait until Mon, 14 Oct 2024 00:28:06 UTC and then assign to @YasogaN and mention Reminder.

**Comment by SnoozeThis** [comment]
Resolved.

@Reminder
