### ISSUE TITLE
Test 1

### ISSUE THREAD

**Issue by tgmpje** [SnoozeThis/playground#3]
test test

**Comment by tgmpje** [comment]
@SnoozeThis wait 10 seconds -> assign label bogus

**Comment by SnoozeThis** [comment]
I would wait until Tue, 08 Mar 2022 19:18:40 UTC and then add label bogus. However, it looks like that has already been resolved.

**Comment by tgmpje** [comment]
@SnoozeThis wait 2 minutes -> assign label bogus

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/OsivjIWFtq0) I will wait until Tue, 08 Mar 2022 19:22:09 UTC and then add label bogus.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by tgmpje** [comment]
@SnoozeThis wait 1 minute -> unassign label bogus, assign label wontfix

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/Ccvt81ERTeQ) I will wait until Tue, 08 Mar 2022 19:32:48 UTC and then add label wontfix.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by tgmpje** [comment]
@SnoozeThis wait 1 minute -> assign label nietbestaandlabel

**Comment by SnoozeThis** [comment]
Unknown label: nietbestaandlabel. Please check syntax or create label first.

**Comment by tgmpje** [comment]
@SnoozeThis wait 1 minute -> remove label wontfix, assign @Jille, add label bogus

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/yhbA5EOMWGw) I will wait until Tue, 08 Mar 2022 19:42:49 UTC and then add label bogus and remove label wontfix.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by tgmpje** [comment]
@SnoozeThis wait 1 minute -> remove label wontfix, assign @Jille, add label bogus

**Comment by SnoozeThis** [comment]
I don't understand "words:{text:"assign" offset:39 end:45} words:{text:"@Jille" offset:46 end:52}"

**Comment by tgmpje** [comment]
@SnoozeThis Wait 1 minute -> assign to @tgmpje

**Comment by SnoozeThis** [comment]
Unknown user: tgmpje

**Comment by tgmpje** [comment]
@SnoozeThis Wait 1 minute -> assign to @tgmpje

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/tdSPLFFaYhc) I will wait until Tue, 08 Mar 2022 20:25:42 UTC and then assign to tgmpje.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by tgmpje** [comment]
@SnoozeThis Wait 1 minute -> assign to @tgmpje, add label bogus, unassign tgmpje

**Comment by SnoozeThis** [comment]
Cannot assign and unassign the same user

**Comment by tgmpje** [comment]
@SnoozeThis Wait 1 minute

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/qEbzdV5fOxo) I will wait until Tue, 08 Mar 2022 20:51:52 UTC and then reassign to you.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by tgmpje** [comment]
@SnoozeThis Wait 1 minute -> assign label bogus

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/nvkRk-Ml-ys) I will wait until Tue, 08 Mar 2022 20:53:14 UTC and then add label bogus.

**Comment by SnoozeThis** [comment]
Resolved.
