### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by Jille** [SnoozeThis/playground#4]
@SnoozeThis wait 1 minute

**Comment by SnoozeThis** [comment]
I would wait until Tue, 22 Mar 2022 21:05:47 CET and then reassign to you. However, it looks like that has already been resolved.

**Comment by Jille** [comment]
@SnoozeThis wait 5 minutes -> close

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/mWg1uaO_ntg) I will wait until Sun, 27 Mar 2022 11:47:45 CEST and then close this issue.

**Comment by Jille** [comment]
[time passes]

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by Jille** [comment]
@SnoozeThis wait 5 minutes -> close

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/WLBjfoAUdA0) I will wait until Mon, 28 Mar 2022 12:11:49 UTC and then close this issue.

**Comment by Jille** [comment]
[time passes]

**Comment by SnoozeThis** [comment]
Resolved.
