### ISSUE TITLE
Second try

### ISSUE THREAD

**Issue by Jille** [SnoozeThis/playground#5]
@SnoozeThis wait 1 minute -> closed

**Comment by SnoozeThis** [comment]
Sorry, I don't understand "closed"

**Comment by Jille** [comment]
@SnoozeThis wait 1 minute -> closed

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/V4tlH4dlOB0) I will wait until Tue, 22 Mar 2022 21:16:13 CET and then close this issue.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by Jille** [comment]
@SnoozeThis wait 5 minutes -> closed

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/v9XgXPIBDHE) I will wait until Tue, 29 Mar 2022 13:06:46 UTC and then close this issue.

**Comment by Jille** [comment]
[time passes]

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by Jille** [comment]
@SnoozeThis wait 5 minutes -> closed

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/_8unm7IMvv0) I will wait until Tue, 29 Mar 2022 13:15:52 UTC and then close this issue.

**Comment by SnoozeThis** [comment]
Resolved.
