### ISSUE TITLE
Testing close

### ISSUE THREAD

**Issue by tgmpje** [SnoozeThis/playground#6]
@SnoozeThis wait 1 second -> close

**Comment by SnoozeThis** [comment]
I would wait until Sun, 27 Mar 2022 15:07:14 UTC and then close this issue. However, it looks like that has already been resolved.

**Comment by tgmpje** [comment]
@SnoozeThis wait 5 seconds -> close

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/4PdNWIb8_ms) I will wait until Sun, 27 Mar 2022 15:07:36 UTC and then close this issue.

**Comment by SnoozeThis** [comment]
Resolved.
